### ISSUE TITLE
发布成功，但是仍然提示deploy失败

### ISSUE THREAD

**Issue by iamazy** [monkeyWie/maven-nexus-release#1]
感谢作者提供这个工具！！！

在使用的过程中遇到一些问题，想咨询一下：
1. 我参考了[proxyee](https://github.com/monkeyWie/proxyee)文件的依赖，发现如果仅靠上面的依赖发布到`Nexus`中无法release，显示`Implicitly created (auto staging)`的错误，按照之前我的发布pom则需要下面的依赖，不知道为啥[proxyee](https://github.com/monkeyWie/proxyee)不需要这个依赖呢

```xml
<plugin>
    <groupId>org.sonatype.plugins</groupId>
    <artifactId>nexus-staging-maven-plugin</artifactId>
    <version>1.6.3</version>
    <extensions>true</extensions>
    <configuration>
         <serverId>releases</serverId>
         <nexusUrl>https://oss.sonatype.org/</nexusUrl>
         <autoReleaseAfterClose>true</autoReleaseAfterClose>
     </configuration>
</plugin>
```
2. 加上了上面依赖，成功发布了，但是action报错如图所示，请问这个是什么问题呢

![image](https://user-images.githubusercontent.com/16559960/99149382-9af51600-26c8-11eb-9926-c6e15df02a66.png)

3. 在`deploy.yml`中版本号必须指定完全(`monkeyWie/maven-nexus-release@v1.0.0`)，不然报找不到，这个没截图

**Comment by monkeyWie** [comment]
`nexus-staging-maven-plugin`插件是自动做`close`和`release`流程的吗，如果是的话我这个action可能白写了🤣，因为它如果帮忙自动发布了话`action`自然就检测不到了。
版本号的我更新下说明文档吧，谢谢指出~

**Comment by iamazy** [comment]
> `nexus-staging-maven-plugin`插件是自动做`close`和`release`流程的吗，如果是的话我这个action可能白写了🤣，因为它如果帮忙自动发布了话`action`自然就检测不到了。
> 版本号的我更新下说明文档吧，谢谢指出~

原来如此，那我再试试不依赖这个action能否发布

**Comment by iamazy** [comment]
哈哈，好像确实不用🤣

**Comment by monkeyWie** [comment]
> 哈哈，好像确实不用🤣

感觉白忙活了，哈哈，以后我也直接用`nexus-staging-maven-plugin`插件试试
